[package]
name = "arknights-downloader"
version = "0.1.0"
edition = "2021"

[dependencies]
aes = "0.8.4"
cbc = "0.1.2"
cipher = "0.4.4"
crossterm = "0.29.0"
hex-literal = "1.1.0"
reqwest = { version = "0.12.24", features = ["blocking", "json"] }
serde = "1.0.228"
serde_json = "1.0.145"
unity-rs = { path = "../unity-rs" }
rayon = "1.11.0"
chrono = "0.4.42"
indicatif = "0.18.3"
rand = "0.9"
crossbeam = "0.8.4"
regex = "1.12.2"
zip = "0.6"
image = "0.24"
bson = "2.11"
clap = { version = "4.5", features = ["derive"] }
